name: Lint, Unit & Instrumented Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_tests:
    runs-on: macos-12

    steps:
      - name: Grant wrapper
        run: chmod +x ./gradlew

      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Lint tests
        run: ./gradlew lint

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          script: ./gradlew connectedDebugAndroidTest
