name: Lint, Unit & Instrumented Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Grant wrapper
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Lint tests
        run: ./gradlew lint

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2.35.0
        with:
          api-level: 36
          script: ./gradlew connectedDebugAndroidTest
